#+TITLE: Understanding decibels
#+AUTHOR: 8dcc
#+STARTUP: nofold
#+HTML_HEAD: <link rel="icon" type="image/x-icon" href="../img/favicon.png">
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/main.css">
#+HTML_LINK_UP: index.html
#+HTML_LINK_HOME: ../index.html
#+LATEX_HEADER: \usepackage{svg}

#+begin_comment org
For more information on how to export this file to PDF, see the comment in
[[file:../programming/pool-allocator.org]].
#+end_comment

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:

The decibel is a unit that is mostly used for audio and signals, but it is often
misunderstood. This article will attempt to explain precisely what it measures,
its different types and how it can be calculated, along with a simple example.

First, it is important to understand that it is a /relative/ unit of measurement,
meaning that it always expresses the relationship between two
quantities. Specifically, it measures the ratio of two values on a logarithmic
scale.

Although it is often used to express absolute "volume" or "signal level", it's
actually expresses the ratio between some variable over a constant. Some of
these constants or "reference values" are listed here, along with their unit
suffixes.

- *dBW*: Measures the relationship between some power in watts and 1 watt.
- *dBm*: Measures the relationship between some power in watts and 1 milliwatt.
- *dBV*: Measures the relationship between a RMS voltage and 1 volt.
- *dBu*: Measures the relationship between a RMS voltage and $\sqrt{0.6}$
  volts[fn:: Specifically, it is the RMS voltage that would dissipate 0 dBm (1
  mW) in a 600 \Omega load. This unit was originally called =dBv=, but was changed
  to =dBu= to avoid confusion with =dBV=.].
- *dBFS*: Measures the relationship between the amplitude of a signal and the
  maximum the device can handle before [[https://en.wikipedia.org/wiki/Clipping_(signal_processing)][clipping]] occurs. The =FS= stands for /Full
  Scale/.
- *dBSPL*: Measures the relationship between a sound pressure and 20 micropascals
  (\mu{}Pa). SPL stands for /Sound Pressure Level/.

Some of these units will be used below, specially those related to voltage and
signal amplitude.

* Calculating decibels
:PROPERTIES:
:CUSTOM_ID: calculating-decibels
:END:

Given two values $a$ and $b$, the decibels can be calculated from their ratio
using the following formula.

\begin{equation}
\label{eq:ratio-to-decibels}
\text{dB} = 20 \log_{10} \left( \frac{a}{b} \right) \\
\end{equation}

Therefore, given the decibels, the ratio between the two values can also be
obtained using a similar formula.

\begin{equation}
\label{eq:decibels-to-ratio}
\frac{a}{b} = 10^{\frac{\text{dB}}{20}}
\end{equation}

* Example
:PROPERTIES:
:CUSTOM_ID: example
:END:

To illustrate this, the following amplifier circuit will be used. An input
signal of $V_{in}$ volts is amplified using a specific [[https://en.wikipedia.org/wiki/Gain_(electronics)][gain]] of $G$ decibels into
an output signal of $V_{out}$ volts[fn::This assumes that the input and output
impedance ($R_{in}$ and $R_{out}$) are equal, which is not always the case.].

#+NAME: fig1
[[file:../img/understanding-decibels1.svg]]

For this example, it will be assumed that the input voltage is 0.3 volts RMS,
the gain of the amplifier is 24 decibels, and the maximum input voltage
supported by the device is 5 volts RMS.

Note how the gain is expressed in decibels, not in "dBV" or "dBFS". This is
because there is no need for a constant or "reference value", the value of the
amplifier simply indicates the ratio that it is supposed to create between the
input and the output voltage after the signal is amplified.

** Calculating the input decibels
:PROPERTIES:
:CUSTOM_ID: calculating-the-input-decibels
:END:

One common misunderstanding about decibels stems from the fact that the input
signal is usually not measured in volts, but in "absolute" decibels using a
constant reference value. In other words, the input is often expressed in dBV or
dBu, but the amplification is expressed in dB, since it measures two variables.

Here are the formulas for calculating different decibels suffixes from a
specific voltage.

| Suffix | Formula                                                   | Example                                                                                     |
|--------+-----------------------------------------------------------+---------------------------------------------------------------------------------------------|
|  <c>   | <l>                                                       | <l>                                                                                         |
|  *dBV*   | $$20 \log_{10} \left( \frac{V_{in}}{1} \right)$$          | $$20 \log_{10} \left( \frac{0.3}{1} \right) = 20 \log_{10}(0.3) \approx -10.45$$            |
|  *dBu*   | $$20 \log_{10} \left( \frac{V_{in}}{\sqrt{0.6}} \right)$$ | $$20 \log_{10} \left( \frac{0.3}{0.774} \right) \approx 20 \log_{10}(0.387) \approx -8.23$$ |
|  *dBFS*  | $$20 \log_{10} \left( \frac{V_{in}}{V_{max}} \right)$$    | $$20 \log_{10} \left( \frac{0.3}{5} \right) = 20 \log_{10}(0.06) \approx -24.43$$           |

All of these values express the same input voltage, 0.3 volts RMS, but they are
expressed relative to different constants. The key detail is that the input
value can't be expressed in decibels without another reference value, which is
usually constant.

Also note how the decibels are usually (but not necessarily always) negative,
since the input voltage is smaller than the reference value. For example, the
maximum dBFS value of a device should be zero, since:

$$
\log_{10} \left( \frac{V_{max}}{V_{max}} \right) = 0
$$

** Calculating the output voltage
:PROPERTIES:
:CUSTOM_ID: calculating-the-output-voltage
:END:

The following figure shows the previous circuit diagram, along with the known
values: the input voltage and the amplifier gain.

#+NAME: fig2
[[file:../img/understanding-decibels2.svg]]

By filling this know data in the formula from the previous section, the ratio
between the input and output voltage can be obtained, and therefore the output
voltage itself.

\begin{align*}
\frac{V_{out}}{V_{in}} &= 10^{\frac{\text{dB}}{20}} \\
\frac{V_{out}}{0.3} &= 10^{\frac{24}{20}} \\
\frac{V_{out}}{0.3} &= 10^{1.2} \\
\frac{V_{out}}{0.3} &\approx 15.84 \\
V_{out} &\approx 0.3 \times 15.84 \\
V_{out} &\approx 4.75 \\
\end{align*}

In the previous formula, 15.84 is the final ratio between the input and output
voltage, which can be applied it to the input to obtain an output value of 4.75
volts. Notice how the output voltage grows logarithmically; it isn't directly
multiplied by 24, which would result in 7.2 output volts RMS.

** Calculating the output dBV
:PROPERTIES:
:CUSTOM_ID: calculating-the-output-dbv
:END:

Similarly to how the input voltage was converted to dBV, the same can be done to
the output voltage.

\begin{split}
\text{dBV} &= 20 \log_{10} \left( \frac{V_{out}}{1} \right) \\
           &= 20 \log_{10} \left( \frac{4.75}{1} \right) \\
           &= 20 \log_{10}(4.75) \\
           &\approx 20 \times 0.67 \\
           &\approx 13.53
\end{split}

Just like with any other value expressed in decibel, this 13.53 expresses a
ratio between two values, in this case the output voltage and a constant
reference value of 1 volt, both RMS. This new value, although expressed in
decibels, is completely independent from the input or the amplification, it
simply indicates a ratio between a signal level and a constant.

Also note that, by subtracting the input and output dBV, the gain can be
obtained. This can be done with a simple subtraction because the input and
output dBV values were calculated using a logarithmic scale, which is also used
to express the gain of the amplifier. In other words, a value expressed in
"suffixed" decibels can be added to another value in "plain" decibels to obtain
a result back in "suffixed" decibels because all decibels use the same
logarithmic formula \eqref{eq:ratio-to-decibels}.
