#+TITLE: Understanding latches and flip-flops
#+AUTHOR: 8dcc
#+STARTUP: nofold
#+HTML_HEAD: <link rel="icon" type="image/x-icon" href="../img/favicon.png">
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/main.css">
#+HTML_HEAD: <script type="text/javascript" src="../js/logic-diagram.js"></script>
#+HTML_LINK_UP: index.html
#+HTML_LINK_HOME: ../index.html

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:

This article covers latches and flip-flops, two kinds of bistable circuits used
in electronics.

Bistable circuits are those which can remain indefinitely stable in one of two
possible states. This can be extremely useful, as it allows the circuit to store
or "remember" a bit of memory (i.e., a digital signal which is high or low, 1 or
0). This is usually accomplished through retroalimentation; some outputs are fed
back into the circuit, self-reinforcing the current state indefinitely.

Note that all diagrams are interactive, and are rendered and simulated in the
browser through [[https://github.com/8dcc/logic-diagram.js][a custom JavaScript library]]; the inputs can be toggled, and the
state of the circuit will change accordingly.

* Latches
:PROPERTIES:
:CUSTOM_ID: latches
:END:

A /latch/ is a bistable circuit that is /level-sensitive/, meaning that a signal
must remain high for the "stored bit" of the circuit to change. Below are some
of the most popular latch circuits, from simplest to most complex.

** SR Latch
:PROPERTIES:
:CUSTOM_ID: sr-latch
:END:

The SR latch is the most basic form of latch, and it is used to built the rest
of the latches and flip-flops in this article.

It has two inputs, /S/ and /R/, which stand for "Set"
and "Reset". When both inputs are low, the circuit outputs its stored value
through /Q/. When input /S/ becomes high, the circuit stores a high signal;
similarly, when input /R/ becomes high, the circuit stores a low signal. The /~Q/
output stores the inverted value of /Q/. Both inputs are not supposed to be high;
that is considered an invalid input, since both /Q/ and /~Q/ would become low.

The circuit is composed of two NOR gates, and the output of each one is fed back
into the other. This is what causes the stabilization, if both inputs are low,
when one of the NOR gates outputs a low signal, it is fed into the other gate,
producing a high signal which is then fed back into the other, keeping that
original signal low indefinitely.

#+begin_export html
<script type="text/logicdiag">
    input R
    input S

    stage 1
    nor nor_A  R nor_B
    nor nor_B  nor_A S

    output nor_A "Q"
    output nor_B "~Q"
</script>
#+end_export

An alternative version of this latch will be shown below. It uses NAND gates
instead of NOR gates, which can be desirable in some scenarios. It uses the same
retroalimentation principle, but the circuit reacts to low inputs instead of
high ones; both /S/ and /R/ are high by default, and a low signal is used to set or
reset the stored value.

** Gated SR Latch
:PROPERTIES:
:CUSTOM_ID: gated-sr-latch
:END:

The gated SR latch is simply a regular SR latch with an extra input /E/, which
controls, through two new AND gates, whether inputs /S/ and /R/ are enabled or
disabled. If the /E/ signal is low, the SR latch doesn't receive any updates from
the other inputs, holding its "stored" value.

#+begin_export html
<script type="text/logicdiag">
    input R
    row 0.5
    input E
    row 1
    input S

    stage 1
    and and_A R E
    and and_B E S

    # SR Latch rectangle
    label "SR Latch" 1.9 -0.6
    rect 1.3 -0.5 2.6 1.5

    # SR Latch
    stage 2
    nor nor_A  and_A nor_B
    nor nor_B  nor_A and_B

    output nor_A "Q"
    output nor_B "~Q"
</script>
#+end_export

An alternative version of the gated SR latch can be built with only 4 NAND
gates. This is convenient in most applications, since NAND gates are cheaper to
fabricate on chips than NOR gates.

In the following diagram, notice how input /S/ is on top, aligned with output /Q/,
and input /R/ is at the bottom, aligned with /~Q/. This is because the entire logic
of the circuit is "inverted"; the two AND gates from the previous circuit are
negated into NAND gates, producing a low signal when both inputs are high. The
NOR gates are just replaced to compensate for this change.

#+begin_export html
<script type="text/logicdiag">
    input S
    row 0.5
    input E
    row 1
    input R

    stage 1
    nand nand_A S E
    nand nand_B E R

    stage 2
    nand nand_C  nand_A nand_D
    nand nand_D  nand_C nand_B

    output nand_C "Q"
    output nand_D "~Q"
</script>
#+end_export

** D Latch
:PROPERTIES:
:CUSTOM_ID: d-latch
:END:

The D latch is similar to the gated SR latch, but inputs /S/ and /R/ are replaced
with a data input /D/. Whenever the /E/ signal is high, the /D/ signal will be stored
directly as the "stored bit" of the circuit.

This is accomplished by negating the /D/ signal and using it as the old "reset"
input, while simultaneously keeping /D/ as the old "set" signal. Therefore, if /D/
is high, then the old /S/ remains high but the old /R/ is negated to low, and
viceversa.

#+begin_export html
<script type="text/logicdiag">
    input D
    input E

    stage 1
    not not_A D
    wire wire_E E 1 0.5
    wire wire_D D 1 1

    # Gated SR Latch rectangle
    label "Gated SR Latch" 2.4 -0.6
    rect 1.3 -0.5 3.6 1.5

    # Gated SR Latch
    stage 2
    and and_A not_A wire_E
    and and_B wire_E wire_D

    stage 3
    nor nor_A and_A nor_B
    nor nor_B nor_A and_B

    output nor_A "Q"
    output nor_B "~Q"
</script>
#+end_export

* Flip-flops
:PROPERTIES:
:CUSTOM_ID: flip-flops
:END:

A /flip-flop/ is a bistable circuit that is /edge-sensitive/, meaning that the
"stored bit" of the circuit is updated whenever a clock signal changes from low
to high. Unlike latches, the data signal is not read during a period of time
(i.e., when the /enable/ signal is high), but at the exact moment when the clock
signal becomes high; if the data signal changes with the clock already high,
those changes are ignored.

This section only covers one of the most popular flip-flop circuits, the D
flip-flop. Note that there are other useful flip-flop circuits like the [[https://en.wikipedia.org/wiki/Flip-flop_(electronics)#JK_flip-flop][JK
flip-flop]].

** D Flip-Flop
:PROPERTIES:
:CUSTOM_ID: d-flip-flop
:END:

The D flip-flop is built with two D latches connected in series, one acting as
"master" and one acting as "slave". They are both connected to the same clock
signal, but the master latch receives it inverted.

#+begin_export html
<script type="text/logicdiag">
    input D
    input CLK

    stage 1
    row 1
    not not_CLK CLK
    wire wire_CLK CLK 0.75 2

    # D Latch 1 rectangle
    label "Master D Latch" 2.9 -0.6
    rect 1.3 -0.5 4.65 1.5

    # D Latch 1
    stage 2
    not not_L1_D D
    wire wire_L1_E not_CLK 2 0.5
    wire wire_L1_D D 2 1

    stage 3
    and and_L1_A not_L1_D  wire_L1_E
    and and_L1_B wire_L1_E wire_L1_D

    stage 4
    nor nor_L1_A and_L1_A nor_L1_B
    nor nor_L1_B nor_L1_A and_L1_B
    output nor_L1_B ~Q1

    stage 5
    wire wire_dst_CLK wire_CLK 5.25 0.5

    # D Latch 2 rectangle
    label "Slave D Latch" 6.9 -0.6
    rect 5.3 -0.5 8.6 1.5

    # D Latch 2
    stage 6
    not not_L2_D nor_L1_A
    wire wire_L2_E wire_dst_CLK 6 0.5
    wire wire_L2_D nor_L1_A 6 1

    stage 7
    and and_L2_A not_L2_D  wire_L2_E
    and and_L2_B wire_L2_E wire_L2_D

    stage 8
    nor nor_L2_A and_L2_A nor_L2_B
    nor nor_L2_B nor_L2_A and_L2_B
    output nor_L2_A Q
    output nor_L2_B ~Q
</script>
#+end_export

This design allows the D flip-flop to only update the stored value at the exact
moment when the /CLK/ signal changes from low to high. The overall behavior of the
circuit is:

1. Clock is low. Master stores values of /D/, but slave holds.
2. Clock becomes high. Master holds, and slave starts storing value from master,
   which won't change while the clock is high.
3. Clock becomes low. Master stores values of /D/, but slave starts holding the
   value it received while the clock was high.

This results in the desired edge-sensitive behavior.

* Comparison
:PROPERTIES:
:CUSTOM_ID: comparison
:END:

As mentioned above, latches are level-sensitive while flip-flops are
edge-triggered. This difference is easier to understand with a timing diagram
which shows how the signals update over time. The following figure compares the
behaviors of a D latch and a D flip-flop under the same inputs. Gray areas are
used to highlight the intervals when the clock or enable signal is high.

#+NAME: fig1
[[file:../img/latches-and-flipflops1.svg]]

Notice how the D flip flop only updates its value at the exact moment when the
/CLK/ changes from low to high, and how the D latch updates whenever /E/ is high.
